### ISSUE TITLE
HTTP Publish never goes through

### ISSUE THREAD

**Issue by swaminathanvasanth** [rbccps-iisc/ideam#213]
```
java.util.concurrent.TimeoutException
	at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77)
	at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:494)
	at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:325)
	at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:270)
	at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:350)
	at com.rabbitmq.client.impl.recovery.RecoveryAwareAMQConnectionFactory.newConnection(RecoveryAwareAMQConnectionFactory.java:64)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.init(AutorecoveringConnection.java:138)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1019)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:978)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:936)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1091)
	at rbccps.smartcity.IDEAM.APIs.publish.run(RequestPublish.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NullPointerException
	at rbccps.smartcity.IDEAM.APIs.publish.run(RequestPublish.java:149)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by swaminathanvasanth** [comment]
RabbitMQ was down due to LDAP connection issue, which caused this response.
